# Generated by Django 3.0.2 on 2021-03-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210309_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='usr',
            new_name='user',
        ),
    ]
