# Generated by Django 3.0.2 on 2020-12-12 13:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='Junkiri Room', max_length=50)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Maintenance', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomInstance',
            fields=[
                ('room_number', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('free_date', models.DateField()),
                ('room', models.ForeignKey(default='Junkiri Room', on_delete=django.db.models.deletion.SET_DEFAULT, to='index.Room')),
                ('status', models.ForeignKey(default='Maintenance', on_delete=django.db.models.deletion.SET_DEFAULT, to='index.RoomStatus')),
            ],
            options={
                'ordering': ['free_date'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='includes',
            field=models.ForeignKey(help_text='services in room, eg:-wifi, tv', null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Service'),
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.RoomType'),
        ),
    ]
