# Generated by Django 3.0.2 on 2020-12-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
