# Generated by Django 3.0.2 on 2020-12-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_room_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(help_text='Junkiri Room', max_length=50),
        ),
        migrations.AlterField(
            model_name='roomstatus',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
