# Generated by Django 3.0.2 on 2020-12-14 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20201214_0728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomstatus',
            options={'verbose_name_plural': 'Room status'},
        ),
    ]
