# Generated by Django 3.0.2 on 2020-12-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20201214_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image_url',
            field=models.ImageField(default='/room_images/default.jpg', upload_to='room_images'),
        ),
        migrations.RemoveField(
            model_name='room',
            name='includes',
        ),
        migrations.AddField(
            model_name='room',
            name='includes',
            field=models.ManyToManyField(help_text='services in room, eg:-wifi, tv', null=True, to='index.Service'),
        ),
        migrations.AlterField(
            model_name='roominstance',
            name='status',
            field=models.CharField(choices=[('B', 'Booked'), ('R', 'Unreserved'), ('M', 'Maintanence')], default='M', max_length=1),
        ),
        migrations.DeleteModel(
            name='RoomStatus',
        ),
    ]
