# Generated by Django 3.0.2 on 2020-12-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20201214_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.ImageField(default='/service_images/default.jpg', upload_to='service_images'),
        ),
    ]
