# Generated by Django 3.0.2 on 2020-12-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20201214_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='includes',
            field=models.ManyToManyField(help_text='services in room, eg:-wifi, tv', to='index.Service'),
        ),
    ]
