# Generated by Django 3.0.2 on 2020-12-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20201214_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominstance',
            name='free_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roominstance',
            name='room_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
