# Generated by Django 3.0.2 on 2020-12-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20201214_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roominstance',
            options={'ordering': ['check_out_date']},
        ),
        migrations.RenameField(
            model_name='roominstance',
            old_name='free_date',
            new_name='check_in_date',
        ),
        migrations.AddField(
            model_name='roominstance',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roominstance',
            name='status',
            field=models.CharField(choices=[('O', 'Occupied'), ('U', 'Unoccupied'), ('M', 'Maintanence')], default='M', max_length=1),
        ),
    ]
