# Generated by Django 3.0.2 on 2020-12-29 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20201217_1108'),
        ('user', '0002_remove_user_u_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.RoomInstance'),
        ),
    ]
