# Generated by Django 3.0.2 on 2021-03-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20201229_1118'),
        ('user', '0003_user_u_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.RoomInstance'),
        ),
    ]
