# Generated by Django 3.0.2 on 2021-03-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210309_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='u_room',
        ),
    ]
