# Generated by Django 3.0.2 on 2021-03-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_u_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='u_room',
        ),
    ]
